import { ArrowUpRight } from 'lucide-react';
import { CATEGORY_LINKS, gygCategoryHref } from '../shared/gyg/picks';
import { useLocale } from '../i18n/useLocale';

/**
 * Direct GetYourGuide category links — generated by
 * scripts/gyg-rollout.mjs on 2026-07-30. Edit the generator, not this file.
 *
 * This site gets category links rather than product cards on purpose: the
 * GetYourGuide supply does not honestly match what the site promises, so naming
 * four specific tours would invent relevance. The reasoning is in picks.ts.
 *
 * Price IS rendered on the product-card sites, but never as ours: it is GetYourGuide's own
 * "from" price on GYG_PRICE_AS_OF, printed with the source and that date beside
 * it. Euros — an earlier note in this codebase claimed USD, which was wrong and
 * came from a JSON-LD field the crawler never stored. No "per person" label:
 * the catalogue does not record the unit and some products are priced per group.
 *
 * Ratings and review counts stay out. We cannot keep them current, and a stale
 * "4.6 (869)" is a claim about other people's experience, not a fact.
 */

const COPY = {
  "kicker": {
    "en": "Book now",
    "fi": "Varaa heti",
    "de": "Jetzt buchen",
    "ja": "今すぐ予約",
    "es": "Reserva ya",
    "pt-BR": "Reserve agora",
    "zh-CN": "立即预订",
    "ko": "지금 예약",
    "fr": "Réservez",
    "it": "Prenoti ora",
    "nl": "Boek nu",
    "sv": "Boka nu"
  },
  "ctaProduct": {
    "en": "Check availability",
    "fi": "Katso saatavuus",
    "de": "Verfügbarkeit prüfen",
    "ja": "空き状況を見る",
    "es": "Ver disponibilidad",
    "pt-BR": "Ver disponibilidade",
    "zh-CN": "查看可订日期",
    "ko": "예약 가능 여부 확인",
    "fr": "Voir les disponibilités",
    "it": "Vedi disponibilità",
    "nl": "Bekijk beschikbaarheid",
    "sv": "Se tillgänglighet"
  },
  "ctaCategory": {
    "en": "Browse all",
    "fi": "Selaa kaikki",
    "de": "Alle ansehen",
    "ja": "すべて見る",
    "es": "Ver todo",
    "pt-BR": "Ver tudo",
    "zh-CN": "查看全部",
    "ko": "전체 보기",
    "fr": "Voir tout",
    "it": "Vedi tutto",
    "nl": "Bekijk alles",
    "sv": "Se alla"
  },
  "via": {
    "en": "via GetYourGuide",
    "fi": "GetYourGuiden kautta",
    "de": "über GetYourGuide",
    "ja": "GetYourGuide 経由",
    "es": "con GetYourGuide",
    "pt-BR": "via GetYourGuide",
    "zh-CN": "通过 GetYourGuide",
    "ko": "GetYourGuide 제공",
    "fr": "via GetYourGuide",
    "it": "tramite GetYourGuide",
    "nl": "via GetYourGuide",
    "sv": "via GetYourGuide"
  },
  "priceFrom": {
    "en": "from",
    "fi": "alkaen",
    "de": "ab",
    "ja": "〜より",
    "es": "desde",
    "pt-BR": "a partir de",
    "zh-CN": "起价",
    "ko": "부터",
    "fr": "à partir de",
    "it": "da",
    "nl": "vanaf",
    "sv": "från"
  },
  "priceSource": {
    "en": "Price on GetYourGuide",
    "fi": "Hinta GetYourGuidessa",
    "de": "Preis auf GetYourGuide",
    "ja": "GetYourGuide の価格",
    "es": "Precio en GetYourGuide",
    "pt-BR": "Preço no GetYourGuide",
    "zh-CN": "GetYourGuide 价格",
    "ko": "GetYourGuide 가격",
    "fr": "Prix sur GetYourGuide",
    "it": "Prezzo su GetYourGuide",
    "nl": "Prijs op GetYourGuide",
    "sv": "Pris på GetYourGuide"
  },
  "headingProduct": {
    "en": "Bookable today",
    "fi": "Varattavissa tänään",
    "de": "Heute buchbar",
    "ja": "今日予約できる体験",
    "es": "Reservable hoy",
    "pt-BR": "Reservável hoje",
    "zh-CN": "今天即可预订",
    "ko": "오늘 예약 가능",
    "fr": "Réservable aujourd’hui",
    "it": "Prenotabile oggi",
    "nl": "Vandaag te boeken",
    "sv": "Bokningsbart i dag"
  },
  "ledeProduct": {
    "en": "Hand-picked dining experiences, bookable online through GetYourGuide.",
    "fi": "Poimitut ruokailuelämykset, varattavissa verkossa GetYourGuiden kautta.",
    "de": "Ausgewählte Kulinarik-Erlebnisse, online über GetYourGuide buchbar.",
    "ja": "厳選したダイニング体験。GetYourGuide でオンライン予約できます。",
    "es": "Experiencias gastronómicas seleccionadas, reservables en línea con GetYourGuide.",
    "pt-BR": "Experiências gastronômicas selecionadas, reserváveis online via GetYourGuide.",
    "zh-CN": "精选餐饮体验，可通过 GetYourGuide 在线预订。",
    "ko": "엄선한 다이닝 체험, GetYourGuide에서 온라인 예약.",
    "fr": "Une sélection d'expériences gastronomiques, réservables en ligne via GetYourGuide.",
    "it": "Esperienze gastronomiche selezionate, prenotabili online tramite GetYourGuide.",
    "nl": "Geselecteerde dinerervaringen, online te boeken via GetYourGuide.",
    "sv": "Utvalda matupplevelser, bokas online via GetYourGuide."
  },
  /**
   * 🔴 Otsikko nimeää HYÖDYN, ei alustaa. Vesa 2026-09-08: *"miksi
   * mainostetaan getyourguidea? aina mainostetaan jotain arvoa mitä turisti
   * saa, ei jotain platformia."* Otsikko oli "Browse and book on
   * GetYourGuide" — se myy kumppanin nimeä lukijalle joka ei tiedä siitä
   * mitään eikä välitä. Sama sääntö kirjattiin laplandvisitissä 7.9. Sembon
   * ja GYG:n mainoksista: *"mainoksen otsikko nimeää hyödyn, ei kumppania."*
   * Kumppani näkyy yhä siellä minne se kuuluu: korttien "via GetYourGuide"
   * -rivillä ja ledessä, ei otsikossa.
   */
  "headingCategory": {
    "en": "Food experiences you can book online",
    "fi": "Ruokaelämyksiä, jotka voi varata verkossa",
    "de": "Kulinarische Erlebnisse, online buchbar",
    "ja": "オンラインで予約できる食の体験",
    "es": "Experiencias gastronómicas que puedes reservar online",
    "pt-BR": "Experiências gastronômicas para reservar online",
    "zh-CN": "可在线预订的美食体验",
    "ko": "온라인으로 예약할 수 있는 미식 체험",
    "fr": "Des expériences culinaires réservables en ligne",
    "it": "Esperienze gastronomiche prenotabili online",
    "nl": "Culinaire ervaringen die u online kunt boeken",
    "sv": "Matupplevelser du kan boka online"
  },
  "ledeCategory": {
    "en": "A partner-maintained list, always current, we do not name a single tour here.",
    "fi": "Kumppanin ylläpitämä lista, aina ajantasainen. Emme nimeä yksittäistä retkeä.",
    "de": "Eine vom Partner gepflegte Liste, immer aktuell.",
    "ja": "パートナーが管理する最新のリストです。",
    "es": "Una lista mantenida por el socio, siempre actualizada.",
    "pt-BR": "Uma lista mantida pelo parceiro, sempre atual.",
    "zh-CN": "由合作伙伴维护的列表，始终保持最新。",
    "ko": "파트너가 관리하는 항상 최신 목록입니다.",
    "fr": "Une liste tenue à jour par le partenaire.",
    "it": "Un elenco aggiornato dal partner.",
    "nl": "Een door de partner bijgehouden, actuele lijst.",
    "sv": "En lista som partnern håller uppdaterad."
  }
};

export default function GygPicks() {
  const { locale: lang } = useLocale();
  const t = (m: Record<string, string>): string => m[lang] ?? m.en;
  const L = COPY;
  const rows = CATEGORY_LINKS['laplanddining-new'] ?? [];

/**
 * Kategorian nimi kortissa.
 *
 * 🔴 Vesa 2026-09-08: *"siis mikä ihme, japania täällä englannin kielellä"* —
 * englanninkielisellä etusivulla luki "음식 & 음료". Korea oli kirjoitettu
 * suoraan en-kenttään, eli vika ei ollut kielivalitsimessa vaan datassa.
 * Fallback (m[lang] ?? m.en) levitti sen JOKAISELLE kielelle jolta rivi
 * puuttui — eli kymmenelle kahdestatoista. Siksi tässä on nyt kaikki 12
 * kieltä niille kahdelle kategorialle jotka tämä sivusto renderöi.
 * Sisarsivusto laplandfood-new oli oikein; vika oli vain täällä.
 */
const CAT_LABEL: Record<string, Record<string, string>> = {
  'ski-snowboard-tc146':      { en: 'Ski & snowboard', fi: 'Hiihto ja lumilautailu' },
  'snow-winter-sports-tc113': { en: 'Snow & winter sports', fi: 'Talviurheilu' },
  'food-drinks-tc103': {
    en: 'Food & drinks', fi: 'Ruoka ja juoma', sv: 'Mat och dryck',
    de: 'Essen & Trinken', fr: 'Gastronomie et boissons', es: 'Comida y bebida',
    it: 'Cibo e bevande', nl: 'Eten en drinken', 'pt-BR': 'Comida e bebida',
    ja: '食べ物と飲み物', ko: '음식과 음료', 'zh-CN': '美食与饮品',
  },
  'dinner-packages-tc100': {
    en: 'Dinner packages', fi: 'Illalliskokonaisuudet', sv: 'Middagspaket',
    de: 'Dinner-Pakete', fr: 'Formules dîner', es: 'Paquetes de cena',
    it: 'Pacchetti cena', nl: 'Dinerarrangementen', 'pt-BR': 'Pacotes de jantar',
    ja: 'ディナーパッケージ', ko: '디너 패키지', 'zh-CN': '晚餐套餐',
  },
  'airport-transfers-tc153':  { en: 'Airport transfers', fi: 'Lentokenttäkuljetukset' },
  'transfers-tc152':          { en: 'Transfers', fi: 'Kuljetukset' },
};
const catName = (path: string, lang: string): string => {
  const key = path.split('/').pop() ?? '';
  const m = CAT_LABEL[key];
  return m ? (m[lang] ?? m.en) : key.replace(/-tc\d+$/, '').replace(/-/g, ' ');
};

  if (!rows.length) return null;

  return (
    <section className="py-16 sm:py-20 px-4 sm:px-6 bg-[#0F172A]">
      {/* Paikallinen taittopoikkeama generaattorista (Vesa 3.8.2026, desktop-
          screenshotit: "aivan kamalan näköiset"): kaksi 620 px leveää laatikkoa
          täysleveillä napeilla max-w-7xl:ssä. Kortit keskitetty max-w-3xl-kehykseen,
          CTA self-center (ei stretch), otsikkolohko keskitetty kuten sivun muut
          osiot. Sama grid+stretch-korjaus viety scripts/gyg-rollout.mjs:ään,
          joten regen ei palauta ongelmaa — vain keskitys on dining-kohtainen. */}
      <div className="max-w-7xl mx-auto">
        <div className="mb-10 sm:mb-12 text-center">
          <p className="font-bold tracking-[0.18em] uppercase text-sm mb-3 text-[#22D3EE]">{t(L.kicker)}</p>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 text-[#F9FAFB]">
            {t(L.headingCategory)}
          </h2>
          <p className="max-w-2xl mx-auto text-white/70">{t(L.ledeCategory)}</p>
        </div>

        <div className="mx-auto grid max-w-3xl gap-5 sm:grid-cols-2">
        {rows.map((c) => (
          <a
            key={c.path}
            href={gygCategoryHref(c, lang)}
            target="_blank"
            rel="sponsored nofollow noopener"
            className="group flex flex-col items-center rounded-2xl border bg-white/5 border-white/10 px-6 py-8 text-center no-underline transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:border-[#22D3EE]/50"
          >
            <h3 className="text-xl font-bold leading-snug text-[#F9FAFB]">{catName(c.path, lang)}</h3>

            <span className="mt-5 inline-flex items-center gap-2 self-center rounded-full bg-[#DB2777] px-6 py-2.5 text-sm font-bold text-white transition-opacity group-hover:opacity-90">
              {t(L.ctaCategory)}
              <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
            </span>

            <span className="mt-3 text-center text-[11px] uppercase tracking-[0.12em] text-white/60">{t(L.via)}</span>
          </a>
        ))}
        </div>
      </div>
    </section>
  );
}
