import mapsData from './generated/restaurants-from-maps.json';
import { restaurantOverrides } from './restaurant-overrides';

/**
 * LaplandDining restaurant catalog.
 *
 * Source data layer (gitted, regenerated by `node scripts/sync-restaurants.mjs`):
 *   src/data/generated/restaurants-from-maps.json — 80 restaurants across 18
 *   Lapland cities, sourced from Google Places API (Text Search + Place Photos).
 *   Each restaurant has rating, review count, price level, opening hours,
 *   address, lat/lng, Maps URL, place ID, photo, last-verified date.
 *
 * Editorial layer (hand-maintained):
 *   src/data/restaurant-overrides.ts — per-Place-ID overrides for partnership
 *   tier (editorial/verified/premium/gold), curated descriptions, hand-picked
 *   menu highlights, dietary flags, cuisine labels.
 *
 * The merged output is what every page consumes via `restaurants` / `cities` /
 * `getTopPicksByCity()` helpers below.
 *
 * Re-sync: `cd laplanddining-new && node scripts/sync-restaurants.mjs`
 *   (Cost: ~$0.60 against the $200/month Google Maps free credit.)
 */

export type PartnershipTier = 'editorial' | 'verified' | 'premium' | 'gold';

export interface Restaurant {
  // Maps-sourced (auto)
  name: string;
  city: string;
  country: string;
  rating?: number;
  reviewCount?: number;
  priceRange?: '€' | '€€' | '€€€' | '€€€€';
  editorialSummary?: string;       // Google's editorial blurb
  website?: string;
  googleMapsUrl: string;
  googlePlaceId: string;
  address: string;
  location: { latitude: number; longitude: number };
  openingHours?: string[];          // weekday descriptions
  photo?: string;                   // /images/restaurants/{slug}.jpg
  slug: string;
  lastVerified: string;             // YYYY-MM-DD
  primaryType?: string;
  types?: string[];

  // Editorial layer (manual overrides, optional)
  topPick: boolean;                 // shown in CityTopPicks home grid
  partnership: PartnershipTier;     // future B2B billing tier
  curatedDescription?: string;      // overrides editorialSummary
  highlights?: string[];            // hand-picked signature items
  cuisine?: string;                 // human-readable cuisine label
  type?: string;                    // human-readable category
  menuHighlights?: { dish: string; price: string; note?: string }[];
  dietary?: ('vegan' | 'vegetarian' | 'gluten-free' | 'lactose-free')[];
  reservationPolicy?: string;
  featured?: boolean;               // legacy alias for topPick where used
}

interface MapsRestaurant {
  name: string;
  city: string;
  country: string;
  topPick: boolean;
  partnership: 'editorial';
  rating?: number;
  reviewCount?: number;
  priceRange?: '€' | '€€' | '€€€' | '€€€€';
  priceLevelRaw?: string;
  editorialSummary?: string;
  website?: string;
  googleMapsUrl: string;
  googlePlaceId: string;
  address: string;
  location: { latitude: number; longitude: number };
  openingHours?: string[];
  photo?: string;
  photosAvailable?: number;
  slug: string;
  lastVerified: string;
  primaryType?: string;
  types?: string[];
}

const merged: Restaurant[] = (mapsData as MapsRestaurant[]).map((m) => {
  const override = restaurantOverrides[m.googlePlaceId] ?? {};
  return {
    ...m,
    ...override,
    // override may not include these required fields — preserve from maps
    name: m.name,
    city: m.city,
    country: m.country,
    googleMapsUrl: m.googleMapsUrl,
    googlePlaceId: m.googlePlaceId,
    address: m.address,
    location: m.location,
    slug: m.slug,
    lastVerified: m.lastVerified,
    // override may flip topPick or upgrade partnership
    topPick: override.topPick ?? m.topPick,
    partnership: override.partnership ?? m.partnership,
    featured: override.topPick ?? m.topPick, // legacy alias
  };
});

/** All restaurants, merged (Maps + editorial overrides). */
export const restaurants: Restaurant[] = merged;

/** All cities with at least one restaurant, in display order. */
export const cities: string[] = [
  'Rovaniemi', 'Levi', 'Kittilä', 'Inari', 'Saariselkä', 'Kemi',
  'Ylläs', 'Tornio', 'Haparanda', 'Sodankylä', 'Pyhätunturi', 'Luosto',
  'Muonio', 'Hetta', 'Kuusamo', 'Kemijärvi', 'Salla', 'Posio',
].filter((c) => restaurants.some((r) => r.city === c));

/** One restaurant per city, ordered as `cities` above. */
export function getTopPicksByCity(): Restaurant[] {
  return cities
    .map((city) => restaurants.find((r) => r.city === city && r.topPick))
    .filter((r): r is Restaurant => Boolean(r));
}

export function getRestaurantsByCity(city: string): Restaurant[] {
  return restaurants.filter((r) => r.city === city);
}

/** Legacy helper kept for /Home `Featured Restaurants` section — top picks of tier-1 cities. */
export function getFeaturedRestaurants(): Restaurant[] {
  const tier1 = ['Rovaniemi', 'Levi', 'Inari', 'Saariselkä', 'Kemi', 'Ylläs'];
  return tier1
    .map((c) => restaurants.find((r) => r.city === c && r.topPick))
    .filter((r): r is Restaurant => Boolean(r));
}

/** Partnership tier helpers for B2B logic + UI badges. */
export function partnershipBadge(tier: PartnershipTier): string | null {
  switch (tier) {
    case 'gold': return '★ Verified Partner';
    case 'premium': return 'Verified Partner';
    case 'verified': return 'Verified Listing';
    default: return null;
  }
}
