import mapsData from './generated/restaurants-from-maps.json';
import { restaurantOverrides } from './restaurant-overrides';

/**
 * LaplandDining restaurant catalog.
 *
 * Source data layer (gitted, regenerated by `node scripts/sync-restaurants.mjs`):
 *   src/data/generated/restaurants-from-maps.json — 80 restaurants across 18
 *   Lapland cities, sourced from Google Places API (Text Search + Place Photos).
 *   Each restaurant has rating, review count, price level, opening hours,
 *   address, lat/lng, Maps URL, place ID, photo, last-verified date.
 *
 * Editorial layer (hand-maintained):
 *   src/data/restaurant-overrides.ts — per-Place-ID overrides for partnership
 *   tier (editorial/verified/premium/gold), curated descriptions, hand-picked
 *   menu highlights, dietary flags, cuisine labels.
 *
 * The merged output is what every page consumes via `restaurants` / `cities` /
 * `getTopPicksByCity()` helpers below.
 *
 * Re-sync: `cd laplanddining-new && node scripts/sync-restaurants.mjs`
 *   (Cost: ~$0.60 against the $200/month Google Maps free credit.)
 */

export type PartnershipTier = 'editorial' | 'verified' | 'premium' | 'gold';

export interface Restaurant {
  // Maps-sourced (auto)
  name: string;
  city: string;
  country: string;
  rating?: number;
  reviewCount?: number;
  priceRange?: '€' | '€€' | '€€€' | '€€€€';
  editorialSummary?: string;       // Google's editorial blurb (only ~10% have it)
  reviewSummary?: string | null;    // Aggregated review summary (Pro tier, often null)
  reviewQuote?: string | null;      // Real customer quote, ~40-180 chars
  website?: string;
  googleMapsUrl: string;
  googlePlaceId: string;
  address: string;
  shortAddress?: string;            // e.g. "Valtakatu 20, Rovaniemi"
  location: { latitude: number; longitude: number };
  openingHours?: string[];          // weekday descriptions
  photo?: string;                   // /images/restaurants/{slug}.jpg
  slug: string;
  lastVerified: string;             // YYYY-MM-DD
  primaryType?: string;
  types?: string[];

  // Editorial layer (manual overrides, optional)
  topPick: boolean;                 // shown in CityTopPicks home grid
  partnership: PartnershipTier;     // future B2B billing tier
  curatedDescription?: string;      // overrides editorialSummary
  highlights?: string[];            // hand-picked signature items
  cuisine?: string;                 // human-readable cuisine label
  type?: string;                    // human-readable category
  menuHighlights?: { dish: string; price: string; note?: string }[];
  dietary?: ('vegan' | 'vegetarian' | 'gluten-free' | 'lactose-free')[];
  reservationPolicy?: string;
  featured?: boolean;               // legacy alias for topPick where used
}

interface MapsRestaurant {
  name: string;
  city: string;
  country: string;
  topPick: boolean;
  partnership: 'editorial';
  rating?: number;
  reviewCount?: number;
  priceRange?: '€' | '€€' | '€€€' | '€€€€';
  priceLevelRaw?: string;
  editorialSummary?: string;
  reviewSummary?: string | null;
  reviewQuote?: string | null;
  website?: string;
  googleMapsUrl: string;
  googlePlaceId: string;
  address: string;
  shortAddress?: string;
  location: { latitude: number; longitude: number };
  openingHours?: string[];
  photo?: string;
  photosAvailable?: number;
  slug: string;
  lastVerified: string;
  primaryType?: string;
  types?: string[];
}

const merged: Restaurant[] = (mapsData as MapsRestaurant[]).map((m) => {
  const override = restaurantOverrides[m.googlePlaceId] ?? {};
  return {
    ...m,
    ...override,
    // override may not include these required fields — preserve from maps
    name: m.name,
    city: m.city,
    country: m.country,
    googleMapsUrl: m.googleMapsUrl,
    googlePlaceId: m.googlePlaceId,
    address: m.address,
    location: m.location,
    slug: m.slug,
    lastVerified: m.lastVerified,
    // override may flip topPick or upgrade partnership
    topPick: override.topPick ?? m.topPick,
    partnership: override.partnership ?? m.partnership,
    featured: override.topPick ?? m.topPick, // legacy alias
  };
});

/** All restaurants, merged (Maps + editorial overrides). */
export const restaurants: Restaurant[] = merged;

/** All cities with at least one restaurant, in display order. */
export const cities: string[] = [
  'Rovaniemi', 'Levi', 'Kittilä', 'Inari', 'Saariselkä', 'Kemi',
  'Ylläs', 'Tornio', 'Haparanda', 'Sodankylä', 'Pyhätunturi', 'Luosto',
  'Muonio', 'Hetta', 'Kuusamo', 'Kemijärvi', 'Salla', 'Posio',
].filter((c) => restaurants.some((r) => r.city === c));

/** One restaurant per city, ordered as `cities` above. */
export function getTopPicksByCity(): Restaurant[] {
  return cities
    .map((city) => restaurants.find((r) => r.city === city && r.topPick))
    .filter((r): r is Restaurant => Boolean(r));
}

export function getRestaurantsByCity(city: string): Restaurant[] {
  return restaurants.filter((r) => r.city === city);
}

/** Legacy helper kept for /Home `Featured Restaurants` section — top picks of tier-1 cities. */
export function getFeaturedRestaurants(): Restaurant[] {
  const tier1 = ['Rovaniemi', 'Levi', 'Inari', 'Saariselkä', 'Kemi', 'Ylläs'];
  return tier1
    .map((c) => restaurants.find((r) => r.city === c && r.topPick))
    .filter((r): r is Restaurant => Boolean(r));
}

/** Partnership tier helpers for B2B logic + UI badges. */
export function partnershipBadge(tier: PartnershipTier): string | null {
  switch (tier) {
    case 'gold': return '★ Verified Partner';
    case 'premium': return 'Verified Partner';
    case 'verified': return 'Verified Listing';
    default: return null;
  }
}

/**
 * Human-friendly cuisine / category label, derived from Maps `types[]` when
 * the editorial layer hasn't supplied one. Filters out generic types like
 * `restaurant`, `food`, `point_of_interest`.
 */
const TYPE_LABELS: Record<string, string> = {
  pizza_restaurant: 'Pizza',
  italian_restaurant: 'Italian',
  finnish_restaurant: 'Finnish',
  scandinavian_restaurant: 'Scandinavian',
  fine_dining_restaurant: 'Fine dining',
  steak_house: 'Steakhouse',
  seafood_restaurant: 'Seafood',
  asian_restaurant: 'Asian',
  chinese_restaurant: 'Chinese',
  japanese_restaurant: 'Japanese',
  thai_restaurant: 'Thai',
  vegetarian_restaurant: 'Vegetarian',
  vegan_restaurant: 'Vegan',
  hamburger_restaurant: 'Burger',
  cafe: 'Café',
  coffee_shop: 'Café',
  bar: 'Bar & restaurant',
  pub: 'Pub & restaurant',
  fast_food_restaurant: 'Casual',
  meal_takeaway: 'Takeaway',
  meal_delivery: 'Delivery',
  bakery: 'Bakery',
};

export function cuisineLabel(r: Restaurant): string | null {
  if (r.cuisine) return r.cuisine;
  if (r.type) return r.type;
  if (!r.types) return null;
  for (const t of r.types) {
    if (TYPE_LABELS[t]) return TYPE_LABELS[t];
  }
  return null;
}

/**
 * Today's opening hours, parsed from regularOpeningHours.weekdayDescriptions
 * (which are localized strings like "Monday: 5:00 – 10:00 PM" or
 * "Wednesday: Closed"). Returns just the time portion, or null if unknown.
 */
const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
export function todayHours(r: Restaurant): string | null {
  if (!r.openingHours || r.openingHours.length === 0) return null;
  const today = WEEKDAYS[new Date().getDay()];
  const entry = r.openingHours.find((d) => d.startsWith(`${today}:`));
  if (!entry) return null;
  const after = entry.slice(today.length + 1).trim();
  return after === 'Closed' ? 'Closed today' : after;
}

/**
 * Compose a 1-2 sentence card body. Priority order:
 *   1. curatedDescription (editorial override)
 *   2. editorialSummary (Google's blurb, only ~10% have it)
 *   3. reviewQuote (real customer voice, in italics, 80%+ have it)
 *   4. synthesized factual line (rating + reviews + priceRange + cuisine)
 */
export interface CardBody {
  text: string;
  isQuote: boolean;
}
export function composeCardBody(r: Restaurant): CardBody | null {
  if (r.curatedDescription) return { text: r.curatedDescription, isQuote: false };
  if (r.editorialSummary) return { text: r.editorialSummary, isQuote: false };
  if (r.reviewQuote) return { text: r.reviewQuote, isQuote: true };
  if (r.rating && r.reviewCount) {
    const cuisine = cuisineLabel(r);
    return {
      text: `${r.rating.toFixed(1)} stars from ${r.reviewCount.toLocaleString('en')} reviews${cuisine ? ` · ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` · ${r.priceRange}` : ''}.`,
      isQuote: false,
    };
  }
  return null;
}
