import mapsData from './generated/restaurants-from-maps.json';
import restaurantImages from './generated/restaurant-images.json';
import restaurantMenus from './generated/restaurant-menus.json';
import { restaurantOverrides } from './restaurant-overrides';
import { restaurantGems } from './restaurant-gems';

type ImageEntry = { src: string; kind: string; credit?: string };
const imageRegistry = restaurantImages as Record<string, ImageEntry>;

type MenuEntry = {
  url?: string; kind?: string; title?: string; evidence?: number;
  status?: string; reason?: string; note?: string; checkedAt: string;
};
const menuRegistry = restaurantMenus as Record<string, MenuEntry>;

/**
 * Ruokalistalinkki rekisterista. Vain `page` ja `pdf` kelpaavat; rivit joilla
 * on `status: 'none'` palauttavat tyhjan, jolloin korttiin ei tule nappia.
 *
 * Rekisteri on avainnettu slugilla samoin kuin kuvarekisteri, koska kasin
 * kuratoitujen gemsien googlePlaceId on tekaistu.
 */
function menuFor(slug: string): { menuUrl?: string; menuKind?: 'page' | 'pdf' } {
  const m = menuRegistry[slug];
  if (!m?.url || (m.kind !== 'page' && m.kind !== 'pdf')) return {};
  return { menuUrl: m.url, menuKind: m.kind };
}

/**
 * LaplandDining restaurant catalog.
 *
 * Source data layer (gitted, regenerated by `node scripts/sync-restaurants.mjs`):
 *   src/data/generated/restaurants-from-maps.json — 80 restaurants across 18
 *   Lapland cities, sourced from Google Places API (Text Search + Place Photos).
 *   Each restaurant has rating, review count, price level, opening hours,
 *   address, lat/lng, Maps URL, place ID, photo, last-verified date.
 *
 * Editorial layer (hand-maintained):
 *   src/data/restaurant-overrides.ts — per-Place-ID overrides for partnership
 *   tier (editorial/verified/premium/gold), curated descriptions, hand-picked
 *   menu highlights, dietary flags, cuisine labels.
 *
 * The merged output is what every page consumes via `restaurants` / `cities` /
 * `getTopPicksByCity()` helpers below.
 *
 * Re-sync: `cd laplanddining-new && node scripts/sync-restaurants.mjs`
 *   (Cost: ~$0.60 against the $200/month Google Maps free credit.)
 */

export type PartnershipTier = 'editorial' | 'verified' | 'premium' | 'gold';

export type Locale = 'en' | 'fi' | 'de' | 'ja' | 'es' | 'pt-BR' | 'zh-CN' | 'ko' | 'fr' | 'it' | 'nl' | 'sv';

/**
 * Localized string — either a single string (legacy = English only)
 * or an object with translations for each supported locale.
 */
export type LocalizedStr =
  | string
  | { en: string; fi: string; de: string; ja?: string; es?: string; 'pt-BR'?: string; 'zh-CN'?: string; ko?: string; fr?: string; it?: string; nl?: string; sv?: string };

/** Pick the right variant out of a LocalizedStr for the given locale. */
export function localizedStr(
  value: LocalizedStr | undefined,
  locale: Locale,
): string | undefined {
  if (value == null) return undefined;
  if (typeof value === 'string') return value;
  return value[locale] ?? value.en;
}

export interface Restaurant {
  // Maps-sourced (auto)
  name: string;
  city: string;
  country: string;
  rating?: number;
  reviewCount?: number;
  priceRange?: '€' | '€€' | '€€€' | '€€€€';
  editorialSummary?: string;       // Google's editorial blurb (only ~10% have it)
  reviewSummary?: string | null;    // Aggregated review summary (Pro tier, often null)
  reviewQuote?: string | null;      // Real customer quote, ~40-180 chars
  website?: string;
  googleMapsUrl: string;
  googlePlaceId: string;
  address: string;
  shortAddress?: string;            // e.g. "Valtakatu 20, Rovaniemi"
  location: { latitude: number; longitude: number };
  openingHours?: string[];          // weekday descriptions
  photo?: string;                   // /images/restaurants/{slug}.webp
  /**
   * Mistä kuva on peräisin. Ratkaisee kuvakaistan alareunan merkinnän.
   *   'partner'      — ravintolan oma og:image, merkintä "Kuva: <domain>"
   *   'illustration' — AI-kuvituskuva, merkintä "Kuvituskuva"
   * Google Place Photos EI ole sallittu lähde: Places API:n käytännöt kieltävät
   * sisällön tallentamisen ja vaativat kuvaajan tekijämerkinnän (vain place_id
   * saa säilöä). Poistettu käytöstä 2026-08-09.
   */
  photoKind?: 'partner' | 'illustration';
  photoCredit?: string;             // esim. "nili.fi" — vain partner-kuville
  /**
   * Ravintolan oma ruokalista. Lähde: generated/restaurant-menus.json, jonka
   * jokainen rivi on kuitattu käsin. 42/87 ravintolalla on linkki; lopuilla
   * rekisterissä on kirjattu syy miksi ei ole.
   */
  menuUrl?: string;
  menuKind?: 'page' | 'pdf';
  slug: string;
  lastVerified: string;             // YYYY-MM-DD
  primaryType?: string;
  types?: string[];

  // Editorial layer (manual overrides, optional)
  topPick: boolean;                 // shown in CityTopPicks home grid
  partnership: PartnershipTier;     // future B2B billing tier
  curatedDescription?: LocalizedStr; // overrides editorialSummary
  highlights?: LocalizedStr[];      // hand-picked signature items (localized; legacy string = EN-only)
  cuisine?: LocalizedStr;           // human-readable cuisine label
  type?: LocalizedStr;              // human-readable category
  menuHighlights?: { dish: string; price: string; note?: string }[];
  dietary?: ('vegan' | 'vegetarian' | 'gluten-free' | 'lactose-free')[];
  reservationPolicy?: string;
  featured?: boolean;               // legacy alias for topPick where used
}

interface MapsRestaurant {
  name: string;
  city: string;
  country: string;
  topPick: boolean;
  partnership: 'editorial';
  rating?: number;
  reviewCount?: number;
  priceRange?: '€' | '€€' | '€€€' | '€€€€';
  priceLevelRaw?: string;
  editorialSummary?: string;
  reviewSummary?: string | null;
  reviewQuote?: string | null;
  website?: string;
  googleMapsUrl: string;
  googlePlaceId: string;
  address: string;
  shortAddress?: string;
  location: { latitude: number; longitude: number };
  openingHours?: string[];
  photo?: string;
  photosAvailable?: number;
  slug: string;
  lastVerified: string;
  primaryType?: string;
  types?: string[];
}

const merged: Restaurant[] = (mapsData as MapsRestaurant[]).map((m) => {
  const override = restaurantOverrides[m.googlePlaceId] ?? {};
  // Kuvarekisteri on ainoa kuvalähde. `m.photo` (Google Place Photo) jätetään
  // tarkoituksella huomiotta — ks. photoKind-kentän kommentti.
  const img = imageRegistry[m.slug];
  const usable = img && (img.kind === 'partner' || img.kind === 'illustration') ? img : undefined;
  return {
    ...m,
    ...override,
    photo: usable?.src,
    photoKind: usable?.kind as 'partner' | 'illustration' | undefined,
    photoCredit: usable?.kind === 'partner' ? usable.credit : undefined,
    ...menuFor(m.slug),
    // override may not include these required fields — preserve from maps
    name: m.name,
    city: m.city,
    country: m.country,
    googleMapsUrl: m.googleMapsUrl,
    googlePlaceId: m.googlePlaceId,
    address: m.address,
    location: m.location,
    slug: m.slug,
    lastVerified: m.lastVerified,
    // override may flip topPick or upgrade partnership
    topPick: override.topPick ?? m.topPick,
    partnership: override.partnership ?? m.partnership,
    featured: override.topPick ?? m.topPick, // legacy alias
  };
});

/**
 * Käsin kuratoidut gems kulkevat saman kuvarekisterin läpi kuin muut.
 * Ilman tätä ne jäisivät ainoiksi kortteiksi ilman kuvamerkintää — ja niiden
 * vanhat .jpg-kuvat olivat tuntematonta alkuperää.
 */
const gemsWithImages: Restaurant[] = restaurantGems.map((g) => {
  const img = imageRegistry[g.slug];
  const usable = img && (img.kind === 'partner' || img.kind === 'illustration') ? img : undefined;
  return {
    ...g,
    ...menuFor(g.slug),
    photo: usable?.src ?? undefined,
    photoKind: usable?.kind as 'partner' | 'illustration' | undefined,
    photoCredit: usable?.kind === 'partner' ? usable.credit : undefined,
  };
});

/** All restaurants, merged (Maps + editorial overrides) plus hand-curated gems. */
export const restaurants: Restaurant[] = [...merged, ...gemsWithImages];

/** All cities with at least one restaurant, in display order. */
export const cities: string[] = [
  'Rovaniemi', 'Levi', 'Kittilä', 'Inari', 'Saariselkä', 'Kemi',
  'Ylläs', 'Tornio', 'Haparanda', 'Sodankylä', 'Pyhätunturi', 'Luosto',
  'Muonio', 'Hetta', 'Kuusamo', 'Kemijärvi', 'Salla', 'Posio',
].filter((c) => restaurants.some((r) => r.city === c));

/** One restaurant per city, ordered as `cities` above. */
export function getTopPicksByCity(): Restaurant[] {
  return cities
    .map((city) => restaurants.find((r) => r.city === city && r.topPick))
    .filter((r): r is Restaurant => Boolean(r));
}

export function getRestaurantsByCity(city: string): Restaurant[] {
  return restaurants.filter((r) => r.city === city);
}

/** Legacy helper kept for /Home `Featured Restaurants` section — top picks of tier-1 cities. */
export function getFeaturedRestaurants(): Restaurant[] {
  const tier1 = ['Rovaniemi', 'Levi', 'Inari', 'Saariselkä', 'Kemi', 'Ylläs'];
  return tier1
    .map((c) => restaurants.find((r) => r.city === c && r.topPick))
    .filter((r): r is Restaurant => Boolean(r));
}

/**
 * Direct link to the Google reviews viewer for a Place. Always opens the
 * full reviews list (not just the place's main panel) so a "627 reviews"
 * pill click goes straight to the customer feedback the user wants to see.
 */
export function googleReviewsUrl(placeId: string): string {
  return `https://search.google.com/local/reviews?placeid=${encodeURIComponent(placeId)}`;
}

/** Partnership tier helpers for B2B logic + UI badges. */
export function partnershipBadge(tier: PartnershipTier): string | null {
  switch (tier) {
    case 'gold': return '★ Featured Partner';
    case 'premium': return 'Featured Partner';
    case 'verified': return 'Featured Listing';
    default: return null;
  }
}

/**
 * Human-friendly cuisine / category label, derived from Maps `types[]` when
 * the editorial layer hasn't supplied one. Filters out generic types like
 * `restaurant`, `food`, `point_of_interest`.
 */
const TYPE_LABELS: Record<string, { en: string; fi: string; de: string; ja: string }> = {
  pizza_restaurant: { en: 'Pizza', fi: 'Pizza', de: 'Pizza', ja: 'ピザ' },
  italian_restaurant: { en: 'Italian', fi: 'Italialainen', de: 'Italienisch', ja: 'イタリアン' },
  finnish_restaurant: { en: 'Finnish', fi: 'Suomalainen', de: 'Finnisch', ja: 'フィンランド料理' },
  scandinavian_restaurant: { en: 'Scandinavian', fi: 'Skandinaavinen', de: 'Skandinavisch', ja: '北欧料理' },
  fine_dining_restaurant: { en: 'Fine dining', fi: 'Fine dining', de: 'Fine Dining', ja: 'ファインダイニング' },
  steak_house: { en: 'Steakhouse', fi: 'Pihviravintola', de: 'Steakhouse', ja: 'ステーキハウス' },
  seafood_restaurant: { en: 'Seafood', fi: 'Merenherkut', de: 'Meeresfrüchte', ja: 'シーフード' },
  asian_restaurant: { en: 'Asian', fi: 'Aasialainen', de: 'Asiatisch', ja: 'アジア料理' },
  chinese_restaurant: { en: 'Chinese', fi: 'Kiinalainen', de: 'Chinesisch', ja: '中華料理' },
  japanese_restaurant: { en: 'Japanese', fi: 'Japanilainen', de: 'Japanisch', ja: '日本料理' },
  thai_restaurant: { en: 'Thai', fi: 'Thai', de: 'Thai', ja: 'タイ料理' },
  vegetarian_restaurant: { en: 'Vegetarian', fi: 'Kasvisravintola', de: 'Vegetarisch', ja: 'ベジタリアン' },
  vegan_restaurant: { en: 'Vegan', fi: 'Vegaani', de: 'Vegan', ja: 'ヴィーガン' },
  hamburger_restaurant: { en: 'Burger', fi: 'Burger', de: 'Burger', ja: 'バーガー' },
  cafe: { en: 'Café', fi: 'Kahvila', de: 'Café', ja: 'カフェ' },
  coffee_shop: { en: 'Café', fi: 'Kahvila', de: 'Café', ja: 'カフェ' },
  bar: { en: 'Bar & restaurant', fi: 'Baari & ravintola', de: 'Bar & Restaurant', ja: 'バー & レストラン' },
  pub: { en: 'Pub & restaurant', fi: 'Pubi & ravintola', de: 'Pub & Restaurant', ja: 'パブ & レストラン' },
  fast_food_restaurant: { en: 'Casual', fi: 'Casual', de: 'Casual', ja: 'カジュアル' },
  meal_takeaway: { en: 'Takeaway', fi: 'Take away', de: 'Zum Mitnehmen', ja: 'テイクアウト' },
  meal_delivery: { en: 'Delivery', fi: 'Kotiinkuljetus', de: 'Lieferung', ja: 'デリバリー' },
  bakery: { en: 'Bakery', fi: 'Leipomo', de: 'Bäckerei', ja: 'ベーカリー' },
};

export function cuisineLabel(r: Restaurant, locale: Locale = 'en'): string | null {
  const cuisine = localizedStr(r.cuisine, locale);
  if (cuisine) return cuisine;
  const type = localizedStr(r.type, locale);
  if (type) return type;
  if (!r.types) return null;
  // Fallback to EN for locales not yet present in TYPE_LABELS (es, pt-BR, zh-CN).
  const labelLocale = (['en', 'fi', 'de', 'ja'] as const).includes(locale as 'en' | 'fi' | 'de' | 'ja')
    ? (locale as 'en' | 'fi' | 'de' | 'ja')
    : 'en';
  for (const t of r.types) {
    if (TYPE_LABELS[t]) return TYPE_LABELS[t][labelLocale];
  }
  return null;
}

/**
 * Today's opening hours, parsed from regularOpeningHours.weekdayDescriptions
 * (which are localized strings like "Monday: 5:00 – 10:00 PM" or
 * "Wednesday: Closed"). Returns just the time portion, or null if unknown.
 */
const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const CLOSED_TODAY: Record<Locale, string> = {
  en: 'Closed today',
  fi: 'Suljettu tänään',
  de: 'Heute geschlossen',
  ja: '本日休業',
  es: 'Cerrado hoy',
  'pt-BR': 'Fechado hoje',
  'zh-CN': '今日休息',
  ko: '오늘 휴무',
  fr: 'Fermé aujourd\'hui',
  it: 'Chiuso oggi',
  nl: 'Vandaag gesloten',
  sv: 'Stängt idag',
};
export function todayHours(r: Restaurant, locale: Locale = 'en'): string | null {
  if (!r.openingHours || r.openingHours.length === 0) return null;
  const today = WEEKDAYS[new Date().getDay()];
  const entry = r.openingHours.find((d) => d.startsWith(`${today}:`));
  if (!entry) return null;
  const after = entry.slice(today.length + 1).trim();
  return after === 'Closed' ? CLOSED_TODAY[locale] : after;
}

/**
 * Compose a 1-2 sentence card body. Priority order:
 *   1. curatedDescription (editorial override)
 *   2. editorialSummary (Google's blurb, only ~10% have it)
 *   3. reviewQuote (real customer voice, in italics, 80%+ have it)
 *   4. synthesized factual line (rating + reviews + priceRange + cuisine)
 */
export interface CardBody {
  text: string;
  isQuote: boolean;
}

const NUMBER_LOCALES: Record<Locale, string> = {
  en: 'en',
  fi: 'fi-FI',
  de: 'de-DE',
  ja: 'ja-JP',
  es: 'es-ES',
  'pt-BR': 'pt-BR',
  'zh-CN': 'zh-CN',
  ko: 'ko-KR',
  fr: 'fr-FR',
  it: 'it-IT',
  nl: 'nl-NL',
  sv: 'sv-SE',
};

/**
 * Synthesised factual line, per locale:
 *   EN: "4.6 stars from 627 reviews · finnish · €€€."
 *   FI: "4.6 tähden arvio • 627 arvostelua • suomalainen • €€€"
 *   DE: "4.6 Sterne • 627 Bewertungen • finnisch • €€€"
 */
function factualLine(r: Restaurant, locale: Locale): string | null {
  if (!r.rating || !r.reviewCount) return null;
  const cuisine = cuisineLabel(r, locale);
  const numLocale = NUMBER_LOCALES[locale];
  const rating = r.rating.toFixed(1);
  const count = r.reviewCount.toLocaleString(numLocale);

  if (locale === 'en') {
    return `${rating} stars from ${count} reviews${cuisine ? ` · ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` · ${r.priceRange}` : ''}.`;
  }
  if (locale === 'fi') {
    return `${rating} tähden arvio • ${count} arvostelua${cuisine ? ` • ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` • ${r.priceRange}` : ''}`;
  }
  if (locale === 'ja') {
    return `評価 ${rating} • レビュー ${count} 件${cuisine ? ` • ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` • ${r.priceRange}` : ''}`;
  }
  if (locale === 'es') {
    return `${rating} estrellas · ${count} reseñas${cuisine ? ` · ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` · ${r.priceRange}` : ''}`;
  }
  if (locale === 'pt-BR') {
    return `${rating} estrelas · ${count} avaliações${cuisine ? ` · ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` · ${r.priceRange}` : ''}`;
  }
  if (locale === 'zh-CN') {
    return `${rating} 星 · ${count} 条评论${cuisine ? ` · ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` · ${r.priceRange}` : ''}`;
  }
  if (locale === 'sv') {
    return `${rating} stjärnor · ${count} recensioner${cuisine ? ` · ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` · ${r.priceRange}` : ''}`;
  }
  // de
  return `${rating} Sterne • ${count} Bewertungen${cuisine ? ` • ${cuisine.toLowerCase()}` : ''}${r.priceRange ? ` • ${r.priceRange}` : ''}`;
}

export function composeCardBody(r: Restaurant, locale: Locale = 'en'): CardBody | null {
  // Always prefer a localized curated description if present
  const curated = localizedStr(r.curatedDescription, locale);
  if (curated) return { text: curated, isQuote: false };

  if (locale === 'en') {
    if (r.editorialSummary) return { text: r.editorialSummary, isQuote: false };
    if (r.reviewQuote) return { text: r.reviewQuote, isQuote: true };
  }
  // FI / DE: editorialSummary + reviewQuote are English-only Google data —
  // skip them and fall through to the synthesised factual line so the card
  // body stays in the user's language.

  const line = factualLine(r, locale);
  if (line) return { text: line, isQuote: false };
  return null;
}

/**
 * Partnership badges. Localized so the FI/DE cards don't show English chrome.
 */
const PARTNERSHIP_LABELS: Record<Locale, Record<Exclude<PartnershipTier, 'editorial'>, string>> = {
  en: {
    gold: '★ Featured Partner',
    premium: 'Featured Partner',
    verified: 'Featured Listing',
  },
  fi: {
    gold: '★ Yhteistyökumppani',
    premium: 'Yhteistyökumppani',
    verified: 'Esittelyssä',
  },
  de: {
    gold: '★ Empfohlener Partner',
    premium: 'Empfohlener Partner',
    verified: 'Empfohlener Eintrag',
  },
  ja: {
    gold: '★ おすすめパートナー',
    premium: 'おすすめパートナー',
    verified: 'おすすめ掲載',
  },
  es: {
    gold: '★ Socio destacado',
    premium: 'Socio destacado',
    verified: 'Ficha destacada',
  },
  'pt-BR': {
    gold: '★ Parceiro em destaque',
    premium: 'Parceiro em destaque',
    verified: 'Listagem em destaque',
  },
  'zh-CN': {
    gold: '★ 推荐合作伙伴',
    premium: '推荐合作伙伴',
    verified: '推荐条目',
  },
  ko: {
    gold: '★ 추천 파트너',
    premium: '추천 파트너',
    verified: '추천 등재',
  },
  fr: {
    gold: '★ Partenaire en vedette',
    premium: 'Partenaire en vedette',
    verified: 'Fiche en vedette',
  },
  it: {
    gold: '★ Partner in evidenza',
    premium: 'Partner in evidenza',
    verified: 'Scheda in evidenza',
  },
  nl: {
    gold: '★ Uitgelichte partner',
    premium: 'Uitgelichte partner',
    verified: 'Uitgelichte vermelding',
  },
  sv: {
    gold: '★ Utvald partner',
    premium: 'Utvald partner',
    verified: 'Utvald listning',
  },
};
export function partnershipBadgeLocalized(tier: PartnershipTier, locale: Locale): string | null {
  if (tier === 'editorial') return null;
  return PARTNERSHIP_LABELS[locale][tier];
}

/**
 * Kuvakaistan alareunan merkintä.
 *
 * AI-kuvituskuva merkitään aina, jotta kortti ei väitä esittävänsä juuri tätä
 * ravintolaa. Kumppanin oma kuva merkitään lähteellä. Merkintä on osa kuvaa,
 * ei erillinen rivi — Vesan ohje 2026-08-09.
 */
const ILLUSTRATION_LABEL: Record<Locale, string> = {
  en: 'Illustration',
  fi: 'Kuvituskuva',
  de: 'Symbolbild',
  ja: 'イメージ画像',
  es: 'Imagen ilustrativa',
  'pt-BR': 'Imagem ilustrativa',
  'zh-CN': '示意图',
  ko: '이미지 사진',
  fr: "Image d'illustration",
  it: 'Immagine illustrativa',
  nl: 'Illustratiebeeld',
  sv: 'Illustrationsbild',
};

const PHOTO_BY: Record<Locale, string> = {
  en: 'Photo', fi: 'Kuva', de: 'Foto', ja: '写真', es: 'Foto', 'pt-BR': 'Foto',
  'zh-CN': '图片', ko: '사진', fr: 'Photo', it: 'Foto', nl: 'Foto', sv: 'Foto',
};

export function photoCaption(r: Restaurant, locale: Locale): string | null {
  if (r.photoKind === 'illustration') return ILLUSTRATION_LABEL[locale];
  if (r.photoKind === 'partner' && r.photoCredit) return `${PHOTO_BY[locale]}: ${r.photoCredit}`;
  return null;
}
